### ISSUE TITLE
SIGINT while waiting for auth to complete results in local echo still turned off.

### ISSUE THREAD

**Issue by dennisjbell** [jhunt/safe#12] opened 2016-04-22 20:24 UTC
Needed to reset terminal to get back to seeing what I've been typing.

**Comment by jhunt** [comment] 2016-06-19 14:47
I'm not able to reproduce this on my OS X environment.  Tried the following:

```
$ safe set secret/x password
password [hidden]: ^C
$ ls
```

(Ctrl-C for a SIGINT at the password prompt)

I also tried via `kill -INT $PID` from another terminal.

In both cases, my terminal gets reset properly.  Can you provide some more repro steps?

**Comment by jhunt** [comment] 2016-06-25 02:18
I was also unable to reproduce this against our (slow) vsphere deployment during the auth phase.

**Comment by jhunt** [comment] 2016-06-25 02:27
Closing due to inability to reproduce.

**Closed by jhunt** 2016-06-25 02:27 UTC
